error: macro "mutex_unlock" passed 2 arguments, but takes just 1
CC      drivers/video/tegra/host/nvhost_syncpt.o
drivers/video/tegra/host/nvhost_syncpt.c: In function
'nvhost_mutex_unlock':
drivers/video/tegra/host/nvhost_syncpt.c:569:34: error: macro
"mutex_unlock" passed 2 arguments, but takes just 1
drivers/video/tegra/host/nvhost_syncpt.c:569:13: error: value computed
is not used [-Werror=unused-value]
cc1: all warnings being treated as errors
make[4]: *** [drivers/video/tegra/host/nvhost_syncpt.o] Error 1
make[3]: *** [drivers/video/tegra/host] Error 2
make[2]: *** [drivers/video/tegra] Error 2
make[1]: *** [drivers/video] Error 2
make: *** [drivers] Error 2